name: Build and Release Flutter Web App

on:
  push:
    branches:
      - master

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Install Dependencies
        run: flutter pub get
        
      - name: Run Build Runner
        run: flutter pub run build_runner build

      - name: Build Flutter Web App
        run: flutter build web --release

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Compress build files
        run: zip -qq -r ./web.zip ./web
        working-directory: ./build

      - name: Get commit count
        id: get_commit_count
        run: echo "count=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: Auto-generated release created by GitHub Actions.
          draft: false
          prerelease: false

      - name: Upload Build Artifacts
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/web.zip
          asset_name: web.zip
          asset_content_type: application/zip